# Generated by Django 5.2.9 on 2025-12-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowleged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='Events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='Alert_alert_status_438782_idx'), models.Index(fields=['created_at'], name='Alert_alert_created_52e56a_idx')],
            },
        ),
    ]
